// Generated by CoffeeScript 2.6.1
//!/usr/bin/env coffee
var DIR;

import {
  join,
  dirname
} from 'path';

import {
  signAsync
} from 'electron-osx-sign';

import thisdir from '@rmw/thisdir';

DIR = thisdir(import.meta);

(async() => {
  var app, entitlements;
  [app] = process.argv.slice(2);
  entitlements = join(DIR, 'i.plist');
  console.log('sign', app);
  await signAsync({
    app,
    verbose: true,
    entitlements,
    'entitlements-inherit': entitlements
  });
  console.log('signed');
  return process.exit();
})();
