import{i as w,b as $,O as z}from"./on.js";import{c as v}from"./record.js";import{d as x,s as d,x as n,q as t,F as p,D as B,v as O,C as T,E as f,z as A,A as D,o as u,l as V,J as E}from"./vendor.js";import{_ as F}from"./index.js";var _,m,g,h,b,k,i,C,S,y,I,j;({recbar:C}=w);y=e=>{var a,s,r;s=e.split(`
`),r=[];for(a of s)r.push(a.split(" "));return r};b=d("00");S=d("00");k=e=>(e+"").padStart(2,"0");[j,I]=(()=>{var e,a;return a=0,e=void 0,[()=>{e=setInterval(()=>{++a,b.value=k(parseInt(a/60)),S.value=k(a%60)},1e3)},()=>{clearInterval(e)}]})();i=d(!1);_=!1;g=d();h={stop:()=>{I(),$.stop(),C.stop()},pause:()=>{var e;({value:e}=i),e=!e,$.pause(i.value=e),!!_&&m(e)}};m=e=>{[j,I][e-0]()};z.start=()=>{j(),_=!0,g.value.className=""};z.pause=e=>{i.value=e,m(e)};var R={setup:()=>{var e,a,s,r,o,c,N;for(s=y(`audio \u9EA6\u514B\u98CE
video \u6444\u50CF\u5934`),c=x(y(`pause \u6682\u505C
stop \u7ED3\u675F\u5F55\u5236
reset \u91CD\u7F6E\u5F55\u5236
cancel \u53D6\u6D88\u5F55\u5236
pen \u753B\u7B14
square \u6846\u9009
left \u6536\u8D77`)),N=l=>()=>{v[l]=v[l]?"":localStorage[l]},o=["audio","video"],a=0,r=o.length;a<r;a++)e=o[a],h[e]=N(e);return{go:l=>{(h[l]||C[l])()},left:s,right:c,code:g,minute:b,second:S,pause:i,config:v}}};const q=e=>(A("data-v-8376417c"),e=e(),D(),e),J={class:"expand"},L=["title","onClick"],G=q(()=>t("b",null,null,-1)),H={class:"pause",ref:"code"},K=q(()=>t("span",null,":",-1)),M=["title","onClick"],P={key:0};function Q(e,a){return u(),n(p,null,[t("div",J,[t("a",{onClick:a[0]||(a[0]=s=>e.go("expand"))})]),t("nav",{class:f({pause:e.pause})},[(u(!0),n(p,null,B(e.left,([s,r],o)=>(u(),n("a",{class:f([s,e.config[s]?"":"x"]),style:V("background-image:url(./"+s+".svg)"),title:r,onClick:c=>e.go(s)},null,14,L))),256)),G,t("code",H,[O(T(e.minute),1),K,O(T(e.second),1)],512),(u(!0),n(p,null,B(e.right,([s,r],o)=>(u(),n(p,null,[t("a",{class:f([s]),style:V("background-image:url(./"+s+".svg)"),title:r,onClick:c=>e.go(s)},null,14,M),[3].indexOf(o)+1?(u(),n("b",P)):E("",!0)],64))),256))],2)],64)}var Z=F(R,[["render",Q],["__scopeId","data-v-8376417c"]]);export{Z as default};
