name: build
on: [push]

jobs:
  build:
    name: build
    strategy:
      matrix:
        # platform: [windows-latest] 
        platform: [macos-latest]
          #platform: [macos-latest,windows-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-node@v2
        with:
          node-version: '17.4.0'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: pip3 install
        run: |
          pip3 install -r requirements.txt

      - name: build
        env:
          accessKeyId: ${{ secrets.accessKeyId }}
          accessKeySecret: ${{ secrets.accessSecret }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: ./dist.sh

    
